apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-portal-config
  namespace: dnd-notes-platform
data:
  API_BASE_PATH: "/portal-api"
  CONTROL_PLANE_URL: "http://dnd-notes-control-plane.dnd-notes-platform.svc.cluster.local:3001"
  KEYCLOAK_URL: "https://keycloak.127.0.0.1.nip.io"
  KEYCLOAK_REALM: "dnd-notes-dev"
  KEYCLOAK_CLIENT_ID: "dnd-notes-customer-portal"
