apiVersion: v1
kind: Service
metadata:
  name: platform-postgres
  namespace: dnd-notes-platform
  labels:
    app.kubernetes.io/name: platform-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: dnd-notes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
