apiVersion: v1
kind: ConfigMap
metadata:
  name: dnd-notes-control-plane-config
  namespace: dnd-notes-platform
data:
  TENANT_BASE_DOMAIN: tenants.example.com
  TENANT_PUBLIC_SCHEME: https
  CONTROL_PLANE_AUTH_MODE: keycloak
  CONTROL_PLANE_KEYCLOAK_URL: https://auth.example.com
  CONTROL_PLANE_KEYCLOAK_JWKS_URL: https://auth.example.com/realms/dnd-notes-workforce/protocol/openid-connect/certs
  CONTROL_PLANE_KEYCLOAK_REALM: dnd-notes-workforce
  CONTROL_PLANE_KEYCLOAK_CLIENT_ID: dnd-notes-control-plane
  CONTROL_PLANE_KEYCLOAK_REQUIRED_ROLES: control-plane-admin,control-plane-workforce
  TENANT_KEYCLOAK_URL: https://auth.example.com
  TENANT_KEYCLOAK_JWKS_URL: https://auth.example.com/realms/dnd-notes/protocol/openid-connect/certs
  TENANT_KEYCLOAK_REALM: dnd-notes
  TENANT_INGRESS_CLASS_NAME: nginx
  KEYCLOAK_ADMIN_BASE_URL: https://auth.example.com
  KEYCLOAK_ADMIN_REALM: dnd-notes
  CUSTOMER_PORTAL_KEYCLOAK_URL: https://auth.example.com
  CUSTOMER_PORTAL_KEYCLOAK_JWKS_URL: https://auth.example.com/realms/dnd-notes/protocol/openid-connect/certs
  CUSTOMER_PORTAL_KEYCLOAK_REALM: dnd-notes
  CUSTOMER_PORTAL_KEYCLOAK_CLIENT_ID: dnd-notes-customer-portal
