apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnd-notes-control-plane
  labels:
    app.kubernetes.io/name: dnd-notes-control-plane
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: dnd-notes
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - configmaps
      - persistentvolumeclaims
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
