apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-portal
  namespace: dnd-notes-platform
  annotations:
    cert-manager.io/cluster-issuer: dev-ca
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - portal.127.0.0.1.nip.io
      secretName: customer-portal-tls
  rules:
    - host: portal.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-portal
                port:
                  name: http
