apiVersion: v1
kind: ConfigMap
metadata:
  name: dnd-notes-control-plane-config
  namespace: dnd-notes-platform
data:
  TENANT_BASE_DOMAIN: 127.0.0.1.nip.io
  TENANT_PUBLIC_SCHEME: https
  CONTROL_PLANE_AUTH_MODE: keycloak
  CONTROL_PLANE_KEYCLOAK_URL: https://keycloak.127.0.0.1.nip.io
  CONTROL_PLANE_KEYCLOAK_JWKS_URL: http://platform-keycloak.dnd-notes-platform.svc.cluster.local:8080/realms/dnd-notes-dev/protocol/openid-connect/certs
  CONTROL_PLANE_KEYCLOAK_REALM: dnd-notes-dev
  CONTROL_PLANE_KEYCLOAK_CLIENT_ID: dnd-notes-control-plane
  CONTROL_PLANE_KEYCLOAK_REQUIRED_ROLES: control-plane-admin,control-plane-workforce
  TENANT_KEYCLOAK_URL: https://keycloak.127.0.0.1.nip.io
  TENANT_KEYCLOAK_JWKS_URL: http://platform-keycloak.dnd-notes-platform.svc.cluster.local:8080/realms/dnd-notes-dev/protocol/openid-connect/certs
  TENANT_KEYCLOAK_REALM: dnd-notes-dev
  TENANT_INGRESS_CLASS_NAME: nginx
  TENANT_TLS_CLUSTER_ISSUER: dev-ca
  KEYCLOAK_ADMIN_BASE_URL: http://platform-keycloak.dnd-notes-platform.svc.cluster.local:8080
  KEYCLOAK_ADMIN_REALM: dnd-notes-dev
  CUSTOMER_PORTAL_KEYCLOAK_URL: https://keycloak.127.0.0.1.nip.io
  CUSTOMER_PORTAL_KEYCLOAK_JWKS_URL: http://platform-keycloak.dnd-notes-platform.svc.cluster.local:8080/realms/dnd-notes-dev/protocol/openid-connect/certs
  CUSTOMER_PORTAL_KEYCLOAK_REALM: dnd-notes-dev
  CUSTOMER_PORTAL_KEYCLOAK_CLIENT_ID: dnd-notes-customer-portal
