apiVersion: v1
kind: Namespace
metadata:
  name: dnd-notes-platform
  labels:
    app.kubernetes.io/part-of: dnd-notes
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/part-of: cert-manager
