apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dnd-notes-activator
  labels:
    app.kubernetes.io/name: dnd-notes-activator
    app.kubernetes.io/component: activator
    app.kubernetes.io/part-of: dnd-notes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dnd-notes-activator
subjects:
  - kind: ServiceAccount
    name: dnd-notes-activator
    namespace: dnd-notes-platform
