apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-portal
  namespace: dnd-notes-platform
  labels:
    app.kubernetes.io/name: customer-portal
    app.kubernetes.io/component: customer-portal
    app.kubernetes.io/part-of: dnd-notes
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - notes.daydreamsoftware.ca
      secretName: daydreamsoftware-wildcard-tls
  rules:
    - host: notes.daydreamsoftware.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-portal
                port:
                  name: http
