apiVersion: v1
kind: Service
metadata:
  name: customer-portal
  namespace: dnd-notes-platform
  labels:
    app.kubernetes.io/name: customer-portal
    app.kubernetes.io/component: customer-portal
    app.kubernetes.io/part-of: dnd-notes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customer-portal
  ports:
    - name: http
      port: 8080
      targetPort: http
