apiVersion: v1
kind: Service
metadata:
  name: platform-keycloak
  namespace: dnd-notes-platform
  labels:
    app.kubernetes.io/name: platform-keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: dnd-notes
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: platform-keycloak
  ports:
    - name: http
      port: 8080
      targetPort: http
