apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-portal
  namespace: dnd-notes-platform
  labels:
    app.kubernetes.io/name: customer-portal
spec:
  ingressClassName: nginx
  rules:
    - host: portal.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-portal
                port:
                  name: http
