apiVersion: batch/v1
kind: CronJob
metadata:
  name: dnd-notes-idle-scaler
  namespace: dnd-notes-platform
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: idle-scaler
              imagePullPolicy: IfNotPresent
