apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../deploy/k3s/base/activator
patches:
  - path: configmap-patch.yaml
  - path: deployment-patch.yaml
  - path: idle-scaler-patch.yaml
images:
  - name: ghcr.io/daydream-software/dnd-notes-activator
    newTag: k3d
