#!/bin/sh
cat <<ENVEOF > /usr/share/nginx/html/env.js
window.__ENV__ = {
  API_BASE_PATH: "${API_BASE_PATH}",
  KEYCLOAK_URL: "${KEYCLOAK_URL}",
  KEYCLOAK_REALM: "${KEYCLOAK_REALM}",
  KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}",
  KEYCLOAK_REQUIRED_ROLES: "${KEYCLOAK_REQUIRED_ROLES}",
  CUSTOMER_PORTAL_URL: "${CUSTOMER_PORTAL_URL}",
  TENANT_BASE_DOMAIN: "${TENANT_BASE_DOMAIN}",
  TENANT_PUBLIC_SCHEME: "${TENANT_PUBLIC_SCHEME}"
};
ENVEOF
